package com.example.account.type;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    USER_NOT_FOUND("NO USER IS FOUND"),
    MAX_ACCOUNT_PER_USER_10("THE MAX USER ACCOUNT IS 10"),
    ACCOUNT_NOT_FOUND("ACCOUNT NUMBER IS NOT FOUND"),
    USER_ACCOUNT_UNMATCH("USER ACCOUNT IS NOT MATCHED"),

    ACCOUNT_ALREDAY_UNREGISTERED("ACCOUNT ALREADY UNREGISTERED"),

    BALANCE_NOT_EMPTY("ACCOUNT BALANCE SHOULD NOT BE EMPTY"), AMOUNT_EXCEED_BALANCE("TRANSACTION AMOUNT IS GREATER THAN THE BALANCE"),
    TRANSACTION_NOT_FOUND("TRANSACTION CANNOT BE FOUND"),
    TRANSACTION_ACCOUNT_UN_MATCH("THE ACCOUNT DOES NOT HAVE TRANSACTION"),
    CANCEL_MUST_FULLY("THE AMOUNT OF CANCEL TRANSACTION DOES NOT MATCH WITH THE TRANSACTION AMOUNT"),
    TOO_OLD_ORDER_TO_CANCEL("TRANSACTION THAT IS PAST ONE YEAR CANNOT BE CANCELED"),
    INVALID_REQUEST("REQUEST MUST BE VALID");
    private final String description;
}
